name: useing1

on:
  repository_dispatch:
    types: [test-reuseing1]

jobs:
  job1:
    uses: ./.github/workflows/reuseing.yml
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo 'This is useing1.'
