name: reuseing

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: "env1"
      secondword:
        description: "The second output string"
        value: "env2"

jobs:
  example_job:
    name: reuseing job
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    steps:
      - id: step1
        run: |
          echo "This is reuseing."
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
